name: flutter_grocery
description: Flutter Grocery App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_staggered_grid_view: ^0.6.2
  fpdart: ^0.5.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  injectable: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true

